[build]
  command = "npm run build"
  publish = "build"
  functions = "server/functions"

[build.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "/.netlify/functions/server/api"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
