services:
  - type: web
    name: esgyy
    env: node
    buildCommand: |
      npm install --force
      npm install -g react-scripts
      npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: CI
        value: false
    staticPublishPath: ./build
